### ISSUE TITLE
Breaking Change Moq 4.11 - SetupAllProperties() (includes Mock.Of<T>) fails in cases it didn't before

### ISSUE THREAD

**Issue by Mexe13** [moq/moq4#845]
Case:

    public class Foo {
         public virtual object Bar { get; internal set; }
    }

    Mock.Of<Foo>();

previously worked. Now it throws:

>Cannot set up Foo.set_Bar because it is not accessible to the proxy generator used by Moq:
Can not create proxy for method Void set_Bar(Foo) because it or its declaring type is not accessible. Make it public, or internal and mark your assembly with [assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")] attribute, because assembly Opc.Ua.Client is not strong-named.
   at Moq.Guard.IsVisibleToProxyFactory(MethodInfo method)
   at Moq.InvocationShape..ctor(LambdaExpression expression, MethodInfo method, IReadOnlyList`1 arguments)
   at Moq.AutoImplementedPropertySetterSetup..ctor(LambdaExpression originalExpression, MethodInfo method, Action`1 setter)
   at Moq.Mock.SetupAllProperties(Mock mock, DefaultValueProvider defaultValueProvider)
   at Moq.Mock.Of[T]()

I assume that previously this was mocked as "readonly property" where `get` could be setuped.
Now Moq tries to mock the same property as a get + set property.

Is this an intended change "here to stay" or will this be reverted?

---------

Also note that when the property is **not** `virtual`, `SetupAllProperties()` will **succeed**. The property is just not mocked. 

    public class Foo {
         public object Bar { get; internal set; }
    }

    Mock.Of<Foo>();

This creates a precedent for "just mock everything mockable". Seems for consistency reasons it might make sense to revert back to the old behavior and "ignore" internal setters?

Thanks!

**Comment by stakx** [comment]
> revert back to the old behavior and "ignore" internal setters

Yes, I believe that's what should happen. Thanks for reporting this regression!

**Comment by BrunoJuchli** [comment]
@stakx 
Thanks a lot for taking the time to looking into the solution. 

After updating to 4.11, it seems the solution is not resolved. The [`Issue845`](https://github.com/moq/moq4/pull/847/commits/027985fe3fed8dd6b9fe93a055acd80818b16a8a) tests fail. I couldn't run them from the moq solution directly *

* build error:
>     Error FS2014: A problem occurred writing the binary 'C:\work\moq4\tests\Moq.Tests.FSharpTypes\obj\Debug\net46\Moq.Tests.FSharpTypes.dll': A call to StrongNameSignatureSize failed (Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED)))

So I created a repro project with just the code from `Issue845` and a package reference to moq 4.11.
All the tests fail with:

> System.ArgumentException
Cannot set up Foo.set_Bar because it is not accessible to the proxy generator used by Moq:
Can not create proxy for method Void set_Bar(System.Object) because it or its declaring type is not accessible. Make it public, or internal and mark your assembly with [assembly: InternalsVisibleTo("DynamicProxyGenAssembly2")] attribute, because assembly MoqIssue845 is not strong-named.
   at Moq.Guard.IsVisibleToProxyFactory(MethodInfo method)
   at Moq.InvocationShape..ctor(LambdaExpression expression, MethodInfo method, IReadOnlyList`1 arguments)
   at Moq.AutoImplementedPropertySetterSetup..ctor(LambdaExpression originalExpression, MethodInfo method, Action`1 setter)
   at Moq.Mock.SetupAllProperties(Mock mock, DefaultValueProvider defaultValueProvider)
   at Moq.Mock`1.SetupAllProperties()
   at MoqIssue845.Issue845.SetupAllProperties_plus_property_access_can_deal_with_internal_setter() in C:\work\MoqIssue845\Issue845.cs:line 37

**Comment by BrunoJuchli** [comment]
Sorry for the previous comment, I was being stupid - didn't notice the fix hasn't been released yet and re-tested it against 4.11, again, and of course found it didn't work...

Thanks for taking the time to fix it!

**Comment by stakx** [comment]
@BrunoJuchli, no worries. I've just released Moq 4.12.0, it should become available on NuGet.org in a few minutes.
